spring:
  application:
    name: userCenter-backend
#   null字段不返回
#  jackson:
#    default-property-inclusion: non_null
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/userCenter?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root  # todo: change your mysql username
    password: 123   # todo: change your mysql pwd
    druid:
      max-wait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    default-property-inclusion: non_null

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
#    关闭下划线查询
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false



